# Generated by Django 5.1.6 on 2025-02-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('meaning', models.TextField()),
                ('example_sentences', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('DE', 'German')], max_length=2)),
                ('difficulty', models.IntegerField(default=1)),
                ('last_reviewed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
